### PR TITLE
Converted the large numbers to a human readable format.

### PR DESCRIPTION
**Pull request by TusharKapoor23**
Fixes issue #12

### CODE REVIEW

**Comment by TusharKapoor23** [comment]
Sorry about the pycache files, forgot to delete them this time. I have changed Thousand -> K, Million -> M, Billion -> B and Trillion -> T.

**Comment by TusharKapoor23** [comment]
Django version shows 2.0.4 and it works on the code on my machine that I have uploaded to github. 

And yes I realize that it should be inside a class. I shall make those changes and make a new commit.

**Comment by TusharKapoor23** [comment]
No problems, Happy to help! Will try to fix other issues as well. Really interested in this project!

**Comment by wingkwong** [comment]
Could you leave an email for discussing the further development plan?

**Comment by TusharKapoor23** [comment]
I have sent you an email from my side.

**Pull request merged**
